 some common terms :
 1. Campus - enitre content
 2. Vocublary - Unique Words
 3. Document  - Line of text - 1row 
 4. word - one word
 

In [6]:
import pandas as pd
import numpy as np

In [7]:
df=pd.DataFrame({
    'text':["I love programming in Python",
             "Python is great for data science",
             "I enjoy learning new programming languages",
             "Data science is an exciting field",
             "Python and data science go hand in hand"]
             ,'output' : [1, 1, 0, 1, 1]
})
df

text  output
0                I love programming in Python       1
1            Python is great for data science       1
2  I enjoy learning new programming languages       0
3           Data science is an exciting field       1
4     Python and data science go hand in hand       1

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [10]:
bow=vectorizer.fit_transform(df['text'])

bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 28 stored elements and shape (5, 19)>

In [12]:
# vocabalory 
print(vectorizer.vocabulary_)

{'love': 14, 'programming': 16, 'in': 10, 'python': 17, 'is': 11, 'great': 8, 'for': 6, 'data': 2, 'science': 18, 'enjoy': 3, 'learning': 13, 'new': 15, 'languages': 12, 'an': 0, 'exciting': 4, 'field': 5, 'and': 1, 'go': 7, 'hand': 9}


In [13]:
bow.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 1]])

In [14]:
bow[0].toarray()  # Example to get the first document's bag-of-words representation

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0]])

In [15]:
#new data transformation
new_data = ["I love data science", "Python is awesome"]
new_bow = vectorizer.transform(new_data)
print(new_bow.toarray())

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]]


# N grams

#### in whihc define the word of combination for tokenization

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2, 2))  # Example for bigrams

In [25]:
bow1=cv.fit_transform(df['text'])
bow1

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24 stored elements and shape (5, 22)>

In [26]:
cv.vocabulary_

{'love programming': 14,
 'programming in': 16,
 'in python': 10,
 'python is': 19,
 'is great': 12,
 'great for': 7,
 'for data': 5,
 'data science': 2,
 'enjoy learning': 3,
 'learning new': 13,
 'new programming': 15,
 'programming languages': 17,
 'science is': 21,
 'is an': 11,
 'an exciting': 0,
 'exciting field': 4,
 'python and': 18,
 'and data': 1,
 'science go': 20,
 'go hand': 6,
 'hand in': 8,
 'in hand': 9}